# Generated by Django 5.2.9 on 2025-12-31 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, choices=[('10A', '10A'), ('10B', '10B'), ('10C', '10C'), ('11A', '11A'), ('11B', '11B'), ('11C', '11C'), ('12A', '12A'), ('12B', '12B'), ('12C', '12C')], max_length=10, null=True),
        ),
    ]
