# Generated by Django 5.2.9 on 2026-01-01 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_student_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ'), ('other', 'Khác')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, choices=[('10A1', '10A1'), ('10A2', '10A2'), ('10A3', '10A3'), ('10C1', '10C1'), ('10C2', '10C2'), ('10C3', '10C3'), ('10C4', '10C4'), ('10C5', '10C5'), ('10D1', '10D1'), ('10D2', '10D2'), ('11A1', '11A1'), ('11A2', '11A2'), ('11A3', '11A3'), ('11C1', '11C1'), ('11C2', '11C2'), ('11C3', '11C3'), ('11C4', '11C4'), ('11C5', '11C5'), ('11D1', '11D1'), ('11D2', '11D2'), ('12A1', '12A1'), ('12A2', '12A2'), ('12A3', '12A3'), ('12C1', '12C1'), ('12C2', '12C2'), ('12C3', '12C3'), ('12C4', '12C4'), ('12C5', '12C5'), ('12D1', '12D1'), ('12D2', '12D2')], max_length=10, null=True),
        ),
    ]
