# Generated by Django 5.2.9 on 2026-01-01 01:49

from django.db import migrations
import random


def populate_gender(apps, schema_editor):
    """Randomly assign gender to all existing users"""
    User = apps.get_model('users', 'User')
    gender_choices = ['male', 'female', 'other']
    
    for user in User.objects.all():
        if not user.gender:  # Only update if gender is not set
            user.gender = random.choice(gender_choices)
            user.save(update_fields=['gender'])


def reverse_populate_gender(apps, schema_editor):
    """Remove gender assignments (optional reverse operation)"""
    User = apps.get_model('users', 'User')
    User.objects.all().update(gender=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_gender_alter_user_student_class'),
    ]

    operations = [
        migrations.RunPython(populate_gender, reverse_populate_gender),
    ]
