# Generated by Django 5.2.9 on 2026-01-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_populate_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress_percent',
            field=models.IntegerField(default=0, help_text='Learning progress percentage (0-100)'),
        ),
    ]
