# Generated by Django 5.2.9 on 2026-01-04 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexam',
            name='allowed_classes',
            field=models.JSONField(default=list, help_text='List of class names allowed to access'),
        ),
        migrations.AddField(
            model_name='activeexam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activeexam',
            name='duration_minutes',
            field=models.IntegerField(default=60, help_text='Duration of the exam in minutes'),
        ),
        migrations.AddField(
            model_name='activeexam',
            name='exam_type',
            field=models.CharField(choices=[('multi_choice', 'Multiple Choice Test'), ('coding', 'Coding Test')], default='multi_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='activeexam',
            name='password',
            field=models.CharField(blank=True, help_text='Optional password to access exam', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='activeexam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='answers',
            field=models.JSONField(default=dict, help_text="Student's answers"),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='stars_earned',
            field=models.IntegerField(default=0, help_text='Stars earned based on score'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='total_questions',
            field=models.IntegerField(default=0, help_text='Total number of questions'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='end_time',
            field=models.DateTimeField(help_text='When the exam disappears from dashboard'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='points_value',
            field=models.IntegerField(default=50, help_text='Maximum stars for perfect score'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='questions',
            field=models.JSONField(help_text='The JSON object containing questions/problems'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='start_time',
            field=models.DateTimeField(help_text='When the exam becomes visible on dashboard'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.activeexam'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='score',
            field=models.IntegerField(default=0, help_text='Number of correct answers'),
        ),
        migrations.AlterField(
            model_name='examsubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='examsubmission',
            unique_together={('exam', 'student')},
        ),
    ]
