# Generated by Django 5.2.9 on 2026-01-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_activeexam_allowed_classes_activeexam_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeexam',
            name='is_ended',
            field=models.BooleanField(default=False, help_text='Teacher can manually end the exam'),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='When the exam disappears from dashboard (optional - leave blank for always visible)', null=True),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When the exam becomes visible on dashboard (optional - leave blank for always visible)', null=True),
        ),
    ]
