# Generated by Django 5.2.9 on 2026-01-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_activeexam_is_ended_alter_activeexam_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='abandoned',
            field=models.BooleanField(default=False, help_text='True if student abandoned the exam (navigated away)'),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='entered_at',
            field=models.DateTimeField(blank=True, help_text='When student entered the exam', null=True),
        ),
        migrations.AddField(
            model_name='examsubmission',
            name='time_spent_seconds',
            field=models.IntegerField(default=0, help_text='Time spent on exam in seconds'),
        ),
    ]
