# Generated by Django 6.0 on 2025-12-26 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('video_mp4', models.FileField(blank=True, null=True, upload_to='lessons/videos/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='lessons/docs/')),
                ('game_html_name', models.CharField(blank=True, help_text='Name of game file in static', max_length=100)),
                ('quiz_data', models.JSONField(blank=True, default=list)),
                ('code_test_data', models.JSONField(blank=True, default=list)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.lesson')),
            ],
            options={
                'verbose_name_plural': 'Progress',
            },
        ),
    ]
