# Generated by Django 6.0 on 2025-12-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='points_value',
            field=models.IntegerField(default=5, help_text='Stars awarded for completing this lesson'),
        ),
    ]
