# Generated by Django 5.2.9 on 2025-12-30 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_lesson_points_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='curriculum.chapter'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='points_value',
            field=models.IntegerField(default=10, help_text='Stars awarded for completing this lesson'),
        ),
    ]
