# Generated by Django 5.2.9 on 2026-01-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_lesson_chapter_alter_lesson_points_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_mp4',
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_id',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=20, null=True),
        ),
    ]
