# Generated by Django 5.2.9 on 2026-01-02 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_populate_quiz_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='code_test_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz_score',
            field=models.IntegerField(default=0, help_text='Number of correct answers'),
        ),
    ]
