# Generated by Django 5.2.9 on 2026-01-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_rename_lesson_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='lessons/docs/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='points_value',
            field=models.IntegerField(default=20, help_text='Stars awarded for completing this lesson'),
        ),
    ]
