# Generated by Django 5.2.9 on 2026-01-05 07:50

import curriculum.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_alter_lesson_pdf_file_alter_lesson_points_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='code_test_passed_at',
            field=models.DateTimeField(blank=True, help_text='When the coding test was passed', null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the lesson was fully completed', null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='quiz_passed_at',
            field=models.DateTimeField(blank=True, help_text='When the quiz was passed', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=500, null=True, storage=curriculum.storage.PdfCloudinaryStorage, upload_to='lessons/docs/'),
        ),
    ]
